version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - $APP_PORT:$APP_PORT
    depends_on:
      - postgres
    container_name: skins_app

  postgres:
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - $DB_PORT:5432
    container_name: skins_db
volumes:
  pgdata:
